import json
from render_junction_v3 import Junction,H,R,save,digest
def read(p):return p.read_text(encoding='utf-8')
def write(p,t):p.write_text(t,encoding='utf-8')
def main():
 s=Junction();fp=s.fingerprint();names=['analytic-validation.json','isolated-validation.json','preview-validation.json','coverage-delivery-validation.json']
 checks={n:json.loads(read(H/n)) for n in names}
 assert all(c['fingerprint']==fp for c in checks.values())
 clips=checks['preview-validation.json']['clips']
 assert clips[0]['validation']['frames']==1800 and clips[1]['validation']['frames']==5400
 assert clips[1]['exact_three_decoded_repetitions']
 for c in clips:assert digest(R/c['path'])==c['sha256']
 inspection='Full-composition temporal/decoded stills, masks and isolated states inspected; continuous playback unavailable. User playback verdict pending.'
 save('delivery-v3.json',{'scene':'The Empty Junction','catalog':11,'version':'v3','date':'2026-10-07','status':'Full minute candidate delivered; user review pending','feedback_v2':"it's ok still overall feels kinda static",'authorization':'do it, following recommendation of ground streamers, cabin exhaust and terrain-guided mist','fingerprint':fp,'preview':clips[0],'repeat_review':clips[1],'validation_records':names,'changes':['Two near-ground mineral streamer routes at 17/22 native px/sec','Condensation from existing right-hand cabin grille, with moving wisps and sixty-second emission variation','Curved valley mist route at 8 native px/sec with near-ridge occlusion'],'retained':'V2 sky, previous far/side mist and habitation match at sampled isolated states; composite outside new masks exact','source_unchanged':True,'new_artwork':None,'inspection':inspection,'limitations':['Grille exhaust is an artistic interpretation','Procedural optical atmosphere is a 2D approximation','Coverage and seam checks do not establish artistic acceptance'],'user_approved':False,'duration_seconds':60,'fps':30,'dimensions':[1280,720],'silent':True,'source_dimensions':[1672,941],'master_4k':None,'music':None,'assembly':None,'remote_backup':None,'credits_spent':0})
 save('visual-review.json',{'preview_sha256':clips[0]['sha256'],'status':'pending_user_playback','inspection':inspection,'observations':['Ground streaks occupy the cabin approach and right-hand service aisle','The plume remains attached to the existing grille and has visibly different concentrations across temporal samples','Valley flow bends behind a nearer ridge','Sky and warm shelter remain compositionally intact'],'pre_delivery_fixes':['Varied exhaust birth intensity to break the initially steady pale streak','Excluded the small trackside post and foreground ridge from their respective weather masks'],'user_approved':False})
 save('feedback.json',{'v2_feedback':"it's ok still overall feels kinda static, brainstoirm a few ideas that could make it better",'execution':'do it','accepted_scope':'Execute recommended three-effect combination; not full preview approval','v3_feedback':None})
 p=R/'final/11-empty-junction/manifest.json';m=json.loads(read(p));m['motion_preparation']['status']='V3 full-minute candidate delivered; user review pending'
 m['animation']={'version':'v3','date':'2026-10-07','status':'Complete minute candidate; user review pending','record':'music/empty-junction-animation-v3/delivery-v3.json','preview':clips[0]['path'],'preview_sha256':clips[0]['sha256'],'repeat_review':clips[1]['path'],'repeat_review_sha256':clips[1]['sha256'],'duration_seconds':60,'fps':30,'dimensions':[1280,720],'silent':True,'seam_checks_passed':True,'user_approved':False,'master_4k':None}
 m['resolution_note']='Native artwork 1672x941; v3 preview 1280x720; 4K awaits complete-preview acceptance.'
 write(p,json.dumps(m,indent=2)+'\n')
 p=R/'final/11-empty-junction/README.md';t=read(p).replace('A complete v2 minute animation candidate is now delivered','A complete v3 minute animation candidate is now delivered')
 a=t.index('Current animation (2026-10-07):')
 t=t[:a]+'''Current animation (2026-10-07): [v3 minute](../../music/empty-junction-animation-v3/empty-junction-v3-preview-60s.mp4), [three-minute join review](../../music/empty-junction-animation-v3/empty-junction-v3-three-loops-180s.mp4), and [scene record/reproduction](../../music/empty-junction-animation-v3/README.md). V2 still felt static to the user. V3 adds mineral streamers across two ground routes, condensation from the existing cabin grille, and curved valley mist with ridge occlusion. V2 sky/weather/lights retained; artwork unchanged. Silent 720p/30 fps. Source protection, retained-layer comparisons, analytical/encoded seams, full decodes/timestamps and exact repeats passed. Assistant inspected stills, not continuous playback. User review pending; 4K follows acceptance with identical motion and disclosed upscaling. Earlier versions preserved. No audio, assembly or remote backup this pass.
'''
 write(p,t)
 p=R/'AGENTS.md';t=read(p);a=t.index('Current Empty Junction animation');b=t.index('\n\n',a)
 current="Current Empty Junction animation (2026-10-07): user said v2 was okay but still felt static, then authorized the recommended ground streamers, cabin exhaust and terrain-guided mist. V3 genuine sixty-second silent 720p/30 fps preview and exact three-repeat 180-second review are delivered in music/empty-junction-animation-v3/; see README.md and delivery-v3.json. Same approved artwork-v2.png SHA-256 ed7b02777c1dcc35504bc0628739688b56515f09ece89d58f299f2dd6013a4be, native 1672x941. Two curved mineral-powder routes at 17/22 native px/sec add near-ground movement. Existing right-hand cabin grille at x520/y389 supplies condensation with ten-second puff lifetimes and minute-wide emission variation; no artwork edit was needed. Grille exhaust is an artistic interpretation. Directed valley mist at 8 native px/sec flows behind a near ridge; small trackside post and turnout equipment occlude powder. V2 sky, previous far/side mist and habitation match at sampled states; full composite outside new masks matches v2. Initial plume looked like a steady streak; variable emission corrected it. Three isolated clips, finite/source-protection checks, analytical states/seams/velocity diagnostics, new-effect coverage into final third, encoded isolated motion, full 1800/5400-frame decoding/timestamps, regional/composite seams and exact repetitions passed. Assistant inspected normal-size temporal/decoded stills and masks, not continuous playback. V3 user review pending; 4K follows full-preview acceptance with identical motion and disclosed upscaling. V1/v2 preserved. Music/assembly separate; no image generation, paid tools, new models, commit/push or remote backup this pass."
 write(p,t[:a]+current+t[b:])
 p=R/'PRODUCTION_PIPELINE.md';t=read(p);line=next(l for l in t.splitlines() if l.startswith('| 11 |'))
 t=t.replace(line,'| 11 | [The Empty Junction](final/11-empty-junction/README.md) | V3 minute and 180-second review delivered: near-ground streamers, cabin grille condensation and terrain-guided mist; v2 retained; technical checks passed | Short/long prompts ready; no audio | Review [v3 full preview](music/empty-junction-animation-v3/README.md); 4K after acceptance |')
 line=next(l for l in t.splitlines() if l.startswith('| 11 Empty Junction |'))
 t=t.replace(line,'| 11 Empty Junction | V3 adds ground powder, grille condensation and curved valley mist over retained v2 weather | Existing station lighting retained; solid geometry fixed. Full minute awaits user playback review. |')
 write(p,t)
 p=R/'creative/ANIMATION_KNOWLEDGE_BANK.md';t=read(p);a=t.index('**Current candidate:**',t.index('### 11 The Empty Junction'));b=t.index('\n\n',a)
 t=t[:a]+"**Current candidate:** [V3](../music/empty-junction-animation-v3/README.md) complete minute and exact 180-second review. V2 still felt static to the user despite wider clouds and mist. User authorized near-ground streamers, cabin condensation and directed valley flow. Technical gates passed; stills inspected, continuous playback and user acceptance pending."+t[b:]
 at=t.index('- V1 had technically sustained weather',a)
 t=t[:at]+'''- V2's wider upper weather did not resolve the static overall impression. V3 redistributes movement nearer the viewer: two mineral streamers beside the tracks and cabin approach, a short grille plume and a specific curved valley flow. The new foreground weather is explicitly authorized for this scene; do not overwrite other scenes' accepted foreground restraint.
- Inspect the source before adding hardware: an existing cabin grille supplies the new plume anchor, avoiding an unnecessary art edit. The capped roof pipe remains unused. Exhaust attribution remains an artistic interpretation.
- Uniform puff spacing made a nearly steady streak. Vary emission at puff birth on minute-periodic schedules, then advect and dissipate the concentrations. Preserve attached roots and inspect the actual full-scene effect. Protect the small trackside post and near ridge as occluders.
'''+t[at:]
 t=t.replace('The source has no readable screen or unambiguously open vent, so those effects remain absent.','The source has no readable screen; the capped roof pipe remains unused. V3 later uses the visible cabin grille as a deliberately interpreted exhaust.')
 t=t.replace('Empty Junction 11 has a technically checked v2 improvement candidate awaiting user review.','Empty Junction 11 has a technically checked v3 motion candidate awaiting user review.')
 write(p,t)
 p=H.parent/'empty-junction-animation-v2/README.md';t=read(p)
 t=t.replace('V2 playback acceptance is pending.', 'User reviewed v2 as okay but still too static. The current [v3 candidate](../empty-junction-animation-v3/README.md) adds nearer motion. V2 remains preserved, without full artistic approval.')
 write(p,t)
 print('V3 delivery and current records saved',flush=True)
if __name__=='__main__':main()
