"""Update current records only after complete v6 delivery checks."""
import json
from render_farpoint_v6 import H,R,save,digest,FarpointV6

def read(p):return p.read_text(encoding='utf-8')
def write(p,t):p.write_text(t,encoding='utf-8')
def replace_paragraph(t,start,new):
 a=t.index(start);b=t.index('\n\n',a);return t[:a]+new+t[b:]

def main():
 s=FarpointV6();fp=s.fingerprint()
 records=['analytic-validation.json','isolated-validation.json','preview-validation.json','targeted-validation.json']
 data={n:json.loads(read(H/n)) for n in records}
 assert all(d['fingerprint']==fp for d in data.values())
 clips=data['preview-validation.json']['clips']
 assert clips[0]['validation']['frames']==1800 and clips[1]['validation']['frames']==5400 and clips[1]['exact_three_decoded_repetitions']
 for c in clips:assert digest(R/c['path'])==c['sha256']
 feedback='music/farpoint-animation-v5/user-feedback-stars-bars-leds-2026-10-07.json'
 write(R/feedback,json.dumps({'date':'2026-10-07','quote':"do it. and i can't see any movement in the star field still, we need to rethink that.  also can we get any LEDS or anything bottom right corner",'attachment':'C:/Users/john/Documents/ShareX/Screenshots/2026-10/ChatGPT_NZyntGEAAa.png','preceding_question':'what is this strange glow?','preceding_attachment':'C:/Users/john/Documents/ShareX/Screenshots/2026-10/ChatGPT_uLJrQlcgcK.png','interpretation':'Do it authorizes removing the previously discussed floating amber bars while preserving the desk lamp. Replace invisible brightness-only stars with positional activity; add bottom-right cabinet LEDs. No new verdict on v5 clouds.','status':'changes_requested','user_approved':False},indent=2)+'\n')
 inspection='Source/mask and normal-size temporal/decoded stills inspected, including cleanup and cabinet details. Continuous playback unavailable. User artistic verdict pending.'
 save('delivery-v6.json',{'scene':'Farpoint Station','catalog':10,'version':'v6','date':'2026-10-07','status':'Complete revised minute candidate; user playback review pending','feedback_record':feedback,'fingerprint':fp,'preview':clips[0],'repeat_review':clips[1],'validation_records':records,'changes':['Three floating amber bars removed through confined generated cleanup','280 source star sprites drift gently right/up with local hidden renewals','Lower-right cabinet strip: steady cyan, independent green and amber activity'],'retained':'Full planet composite and original weather/station layer regions match v5 at sampled times; no new cloud approval inferred','inspection':inspection,'user_approved':False,'master_4k':None,'native_source_size':[1672,941],'preview_size':[1280,720],'fps':30,'silent':True,'asset_provenance':'asset-provenance.json','image_generation_mode':'built-in image_gen edit','music':None,'assembly':None,'remote_backup':None,'credits_spent':0})
 save('visual-review.json',{'status':'pending_user_playback','preview_sha256':clips[0]['sha256'],'inspection':inspection,'observations':['Queried bright bars absent; lamp, desk spill and window structure remain','Star positions change together right/up in temporal frames','Cabinet status strip stays attached, with localized glow and independent lights','No aurora; v5 clouds and existing station effects retained'],'limitations':['Local zero-opacity star renewals are a cinematic loop approximation','Tracking and seam statistics are technical evidence, not proof of readable or natural movement','New cleanup, LEDs and full minute remain unapproved'],'trial_correction':'Initial direct patch blend created dark ovals; Poisson colour/gradient matching fixed the local mismatch before encoding'})
 p=H.parent/'farpoint-animation-v5/visual-review.json';d=json.loads(read(p));d['status']='changes_requested';d['feedback_record']=feedback;d['acceptance_scope']='Star motion still imperceptible; remove bars and add cabinet LEDs. No new planet verdict.';write(p,json.dumps(d,indent=2)+'\n')
 p=H.parent/'farpoint-animation-v5/delivery-v5.json';d=json.loads(read(p));d['status']='User requested star rethink, bar removal and cabinet LEDs';d['latest_feedback_record']=feedback;write(p,json.dumps(d,indent=2)+'\n')
 p=H.parent/'farpoint-animation-v5/README.md';t=read(p);note='Latest verdict: star movement was still imperceptible. The user authorized bar removal and requested lower-right cabinet LEDs. No new cloud verdict was given. See [exact feedback](user-feedback-stars-bars-leds-2026-10-07.json) and [v6 delivery](../farpoint-animation-v6/README.md). V5 is superseded and not accepted.\n\n'
 if note not in t:
  at=t.index('\n\n')+2;t=t[:at]+note+t[at:]
 t=t.replace('User playback review is pending.','User requested changes; see the current verdict above.')
 write(p,t)
 p=R/'final/10-nightward-station/manifest.json';m=json.loads(read(p))
 if m['animation']['version']=='v5':
  m['animation']['status']='User requested positional star activity, bar cleanup and cabinet LEDs';m['animation']['feedback_record']=feedback;m['animation_history'].append(m['animation'])
 else:assert m['animation']['version']=='v6'
 m['animation']={'version':'v6','date':'2026-10-07','status':'Revised minute candidate; user playback review pending','record':'music/farpoint-animation-v6/delivery-v6.json','preview':clips[0]['path'],'preview_sha256':clips[0]['sha256'],'repeat_review':clips[1]['path'],'repeat_review_sha256':clips[1]['sha256'],'duration_seconds':60,'fps':30,'dimensions':[1280,720],'silent':True,'seam_checks_passed':True,'user_approved':False,'master_4k':None}
 m['animation_source']={**s.config['source'],'provenance':'music/farpoint-animation-v6/asset-provenance.json','scope':'User-authorized narrow bar cleanup; original packaging artwork remains unchanged','user_approved':False}
 write(p,json.dumps(m,indent=2)+'\n')
 p=R/'AGENTS.md';t=read(p)
 current="Current Farpoint animation (2026-10-07): v5's stronger brightness-only stars still failed the user's visibility review. User authorized removal of the floating amber bars beside the monitor and requested LEDs on the bottom-right cabinet. V6 genuine sixty-second 720p/30 fps silent preview and exact three-repeat 180-second review are delivered in music/farpoint-animation-v6/; see README.md and delivery-v6.json. 280 extracted source stars move right/up at 1.25/-.13 native px/sec, about 7.66/-.80 preview pixels per eight seconds; independent zero-opacity renewals close the minute. Cinematic approximation, not celestial simulation. New door-mounted strip has steady cyan power, green acknowledgements and amber holds. Core and local spill share states. Floating bars removed using a confined built-in imagegen patch with gradient matching; first direct blend left dark ovals and is preserved as a failed internal candidate. Active animation source is final/10-nightward-station/artwork-v4b-reflection-cleanup.png, SHA-256 8eeffb7e02a09c61604b8ed36309eda86585f707b83e94dedab3db45c5f83247, native 1672x941. All pixels outside its small cleanup mask exactly match original v3 artwork; lamp and desk spill preserved. Original packaging art/thumbs retained. V5 full planet composite and weather/station layer regions match at 0/7/20/40/54 seconds; no new cloud approval inferred. Aurora remains removed. Analytical seams/protection/regressions, encoded positional tracking, full 1800/5400-frame decoding/timestamps, regional/composite encoded seams and exact three-cycle repetition passed. Assistant inspected normal-size temporal/decoded stills and detail/mask images, not continuous playback. V6 playback review pending; user confirmation still covers only v2 cloud visibility. 4K follows full-preview acceptance with identical motion and disclosed upscaling. Music/assembly separate. Historical source/code/media and feedback preserved. No paid services/model installation, commit/push or remote backup this pass."
 write(p,replace_paragraph(t,'Current Farpoint animation',current))
 p=R/'PRODUCTION_PIPELINE.md';t=read(p)
 line=next(x for x in t.splitlines() if x.startswith('| 10 |'))
 t=t.replace(line,'| 10 | [Farpoint Station](final/10-nightward-station/README.md) | V6 minute and 180-second review delivered: drifting stars, bar cleanup, lower-right cabinet LEDs; v5 planet retained; technical checks passed | Short/long prompts ready; no audio | Review [v6 complete preview](music/farpoint-animation-v6/README.md); 4K after acceptance |')
 line=next(x for x in t.splitlines() if x.startswith('| 10 Farpoint |'))
 t=t.replace(line,'| 10 Farpoint | V5 cloud fronts and original weather retained; no aurora | Stars now travel right/up; floating amber bars removed; new cabinet LEDs. Existing monitor/lamp/station activity retained. V6 full minute awaits playback review. |')
 write(p,t)
 p=R/'final/10-nightward-station/README.md';t=read(p);a=t.index('Current clean artwork:');b=t.index('Thumbnail:')
 current="""Current clean artwork: the original [artwork-v3-close-world-leds.png](artwork-v3-close-world-leds.png) remains the packaging source. V6 animation uses [artwork-v4b-reflection-cleanup.png](artwork-v4b-reflection-cleanup.png), a confined removal of the three queried amber bars. Pixels outside the cleanup mask, including the lamp and desk spill, are unchanged. See [exact prompt and provenance](../../music/farpoint-animation-v6/asset-provenance.json). The earlier v4 cleanup plate is a failed internal blend, not the active source.

Current animation: [v6 complete minute](../../music/farpoint-animation-v6/farpoint-station-v6-preview-60s.mp4), [180-second join review](../../music/farpoint-animation-v6/farpoint-station-v6-three-loops-180s.mp4), and [scene record/checks](../../music/farpoint-animation-v6/README.md). Silent 1280x720/30 fps. Stars now drift gently right/up, and a lower-right cabinet status strip has steady cyan power plus independent green/amber events. V5 weather and original station activity are retained. The rejected aurora stays absent.

V1 invisible-motion failure, v2 confirmed cloud visibility, v4 coverage/glow rejection and v5 invisible star feedback remain in history. Technical gates passed; assistant inspected temporal/decoded stills, not continuous playback. V6 user review is pending. Export 4K only after acceptance, with identical motion and disclosed upscaling from 1672x941. No soundtrack or long assembly yet.

"""
 write(p,t[:a]+current+t[b:])
 p=R/'creative/ANIMATION_KNOWLEDGE_BANK.md';t=read(p);start=t.index('### 10 Farpoint Station');a=t.index('**Current state:**',start);b=t.index('\n\n',a)
 current="**Current state:** v1 motion was rejected as invisible; v2 cloud visibility was confirmed. V3 still read as clouds alone. V4 was rejected for sparse coverage, blue auroral glow and imperceptible stars. V5 removed the aurora and expanded weather, but stronger fixed-star brightness still failed the user's movement review. [V6](../music/farpoint-animation-v6/README.md) delivers a complete minute and exact 180-second review with positional star drift, confined amber-bar cleanup and bottom-right cabinet LEDs. V5 planet and existing station activity retained. Technical gates passed; user playback review and 4K pending. Assistant inspected stills, not continuous playback."
 t=t[:a]+current+t[b:]
 t=t.replace('v4 now implements them as candidates awaiting user playback review.','v4 implemented them; the user subsequently rejected the aurora as an implausible blue glow.')
 t=t.replace('V4 now links their complete bright cores and local haze to the desk lamp.','V4 linked their complete bright cores and local haze to the desk lamp; the user later authorized removing the confusing bars in v6.')
 old='- Nineteen-percent modulation of six tiny star cores was invisible to the user. V5 uses stronger independent 10–20-second light changes on those original stars, preserving positions and footprints. Check the encoded 720p brightness range and real playback; a nonzero source-pixel delta is insufficient.'
 new="- Both v4 subtle modulation and v5 stronger fixed-star brightness failed the user's movement review. Large encoded brightness ranges did not answer a positional-motion expectation. V6 transports extracted source star sprites together right/up while keeping camera and geometry fixed; native footprints are preserved with subpixel sampling. Local zero-opacity renewals close the minute. This is a cinematic approximation pending playback review, not a proven preset. [Feedback](../music/farpoint-animation-v5/user-feedback-stars-bars-leds-2026-10-07.json) and [encoded transport evidence](../music/farpoint-animation-v6/targeted-validation.json).\n- Ambiguous source reflections can remain confusing after correct lamp-linked dimming. V6 removes only the queried bars using a generated patch and source-coordinate mask. Direct blending caused dark ovals; gradient matching corrected the surrounding glass. Freeze the revised plate/hash, remap and disable obsolete reflection masks, prove unchanged pixels outside the edit, and inspect the full composition.\n- New cabinet LEDs were explicitly requested. V6 places a small housing along the door perspective, with one steady light, independent events and attached local spill. Do not scatter unsupported bright dots over bare panels. Sampled full-planet and supporting-layer comparisons protect earlier motion while these additions change."
 assert old in t;t=t.replace(old,new)
 t=t.replace("v5's revised full minute awaits playback review, with technical evidence recorded.","v5 stars were still imperceptible; v6's positional stars, bar cleanup and cabinet LEDs await full-preview review, with technical evidence recorded.")
 write(p,t)
 print('V6 delivery and current production records updated',flush=True)
if __name__=='__main__':main()
