"""Save actual completion evidence and update current authority after validation."""
import json
from render_farpoint_v4 import H,R,save,digest,FarpointMinute

def main():
 s=FarpointMinute();fp=s.fingerprint()
 reports={n:json.loads((H/n).read_text()) for n in ['analytic-validation.json','preview-validation.json','supplemental-validation.json','corrected-isolated-validation.json','isolated-validation.json']}
 assert all(reports[n]['fingerprint']==fp for n in list(reports)[:-1])
 p=reports['preview-validation.json'];clips=p['clips']
 assert clips[0]['validation']['frames']==1800 and clips[1]['validation']['frames']==5400 and clips[1]['exact_three_decoded_repetitions']
 for c in clips:assert digest(R/c['path'])==c['sha256']
 snapshot=H/'renderer-before-reflection-mask-correction.py'
 assert digest(snapshot)==reports['isolated-validation.json']['fingerprint']['files']['music/farpoint-animation-v4/render_farpoint_v4.py']
 inspection='Source, masks, forced-dark and actual-strength 720p temporal/decoded stills inspected. Continuous playback unavailable; user artistic review pending.'
 record={'scene':'Farpoint Station','catalog':10,'version':'v4','date':'2026-10-07','status':'Complete 60-second 720p visual-loop candidate; user playback review pending','authorization':'User invoked FARPOINT STATION — FINISH THE SCENE and completion prompt v2','fingerprint':fp,'preview':clips[0],'repeat_review':clips[1],'validation_records':list(reports),'initial_diagnostic_renderer':{'path':snapshot.relative_to(R).as_posix(),'sha256':digest(snapshot)},'inspection':inspection,'user_approved':False,'prior_acceptance_scope':'V2 cloud visibility only; v3 additional clouds/shadows did not establish a distinct planetary phenomenon','master_4k':None,'next_gate':'User accepts the complete minute preview, then export identical settings to silent 4K and validate','native_source_size':[1672,941],'preview_size':[1280,720],'fps':30,'silent':True,'music':None,'assembly':None,'remote_backup':None,'credits_spent':0}
 save('delivery-v4.json',record)
 save('visual-review.json',{'status':'pending_user_playback','preview_sha256':clips[0]['sha256'],'assistant_inspection':inspection,'stills_findings':['Irregular teal folds remain on the dark planetary arc; limb/cabin geometry fixed','Cloud texture changes position across samples including final third; terrain reconstruction approximate','Amber reflection cores and lamp dim together; source-brightness gating avoids rectangular glass darkening','Small monitor actions retain source schematic/perspective; light schedules include quiet holds'],'initial_fixes':['Regular aurora comb replaced by seeded irregular spacing, widths/heights, gentle curvature and softened detail','Middle storm moved from thin cloud to the optical formation present at that time','Reflection mask excludes dark glass but includes white cores'],'not_claimed':['continuous playback inspection','user approval','4K export','remote backup']})
 path=R/'final/10-nightward-station/manifest.json';m=json.loads(path.read_text(encoding='utf-8'));assert m['animation']['version'] in ['v3','v4']
 if m['animation']['version']=='v3':m['animation_history'].append(m['animation'])
 m['animation']={'version':'v4','date':'2026-10-07','status':record['status'],'record':'music/farpoint-animation-v4/delivery-v4.json','preview':clips[0]['path'],'preview_sha256':clips[0]['sha256'],'repeat_review':clips[1]['path'],'repeat_review_sha256':clips[1]['sha256'],'duration_seconds':60,'fps':30,'dimensions':[1280,720],'silent':True,'seam_checks_passed':True,'user_approved':False,'master_4k':None};path.write_text(json.dumps(m,indent=2)+'\n')
 path=R/'AGENTS.md';text=path.read_text(encoding='utf-8');start=text.index('Current Farpoint animation');end=text.index('\n\n',start)
 current="Current Farpoint animation (2026-10-07): user invoked the completion prompt. V4 genuine sixty-second 720p/30 fps silent preview and exact three-repeat 180-second review are delivered in music/farpoint-animation-v4/; see README.md and delivery-v4.json. Adds irregular blue-green auroral folds on the dark left planetary arc, three sparse intracloud light events, six fixed-position stars with shallow variation, lamp-linked original amber glass reflections, purposeful monitor activity and independent minute-wide instrument/window holds. V2/v3 cloud extraction, optical data and velocity field retained exactly; six separate formations now use staggered sixty-second lifetimes and local zero-opacity resets, so the composite is not pixel-identical to the forward prototypes. Lower-cloud speed and foreground crater exclusion retained. Source unchanged, SHA-256 9728b8a9baa773365b2eff1a7b0bb030836050f02309e4a04e29bae6d2104c4b, native 1672x941. Initial aurora comb and reflection-mask dark rectangles corrected before delivery. Analytical seams, protected pixels, retained arrays/masks, distinct 0/20/40 states, final-third activity, full 1800/5400-frame decoding/timestamps, encoded regional/composite seams and exact decoded repetitions passed. Assistant inspected masks/forced-dark/temporal/decoded stills, not continuous playback. User confirmation covers v2 cloud visibility only; v4 look and minute timing await review. Export the 4K minute only after acceptance, with identical motion and disclosed upscaling. Music and assembly remain separate. V1 invisible-motion rejection, v3 clouds-only feedback and all historical art/code/videos preserved. No paid tools, credits, model installation, commit/push or remote backup in this pass."
 path.write_text(text[:start]+current+text[end:],encoding='utf-8')
 path=R/'PRODUCTION_PIPELINE.md';text=path.read_text(encoding='utf-8');old=next(x for x in text.splitlines() if x.startswith('| 10 |'))
 new='| 10 | [Farpoint Station](final/10-nightward-station/README.md) | V4 genuine sixty-second 720p loop and exact 180-second review delivered; aurora, storms, stars, linked reflections and minute instrumentation; technical checks passed, user review pending | Short/long prompts ready; no audio | Review [complete v4 minute](music/farpoint-animation-v4/README.md) and joins; after acceptance export silent 4K with identical settings |'
 path.write_text(text.replace(old,new),encoding='utf-8')
 path=R/'final/10-nightward-station/README.md';text=path.read_text(encoding='utf-8');start=text.index('Current clean artwork:');end=text.index('Thumbnail:')
 current="""Current clean artwork: [artwork-v3-close-world-leds.png](artwork-v3-close-world-leds.png). Source remains unchanged. V1 motion was rejected as invisible; the user confirmed v2 cloud visibility. V3 additions still read as clouds alone on the planet. Earlier versions remain preserved.

Current animation: [v4 full sixty-second preview](../../music/farpoint-animation-v4/farpoint-station-v4-preview-60s.mp4), [three-repeat 180-second join review](../../music/farpoint-animation-v4/farpoint-station-v4-three-loops-180s.mp4), and [scene record/checks](../../music/farpoint-animation-v4/README.md). Silent 1280x720/30 fps. The invoked [completion prompt v2](animation-completion-prompt-v2.txt) now has a genuine minute candidate with travelling clouds, irregular auroral folds, three cloud-local light events, gentle star variation, lamp-linked amber reflections, schematic/dial/log activity and independent light holds.

Full decoding/timestamps, protected pixels, analytical/encoded seams and exact three-cycle identity passed. Assistant inspected masks and temporal/decoded stills, not continuous playback. User review of the complete minute is pending; 4K follows acceptance with identical motion, upscaled from native 1672x941. No music, long assembly or remote backup is implied.

"""
 path.write_text(text[:start]+current+text[end:],encoding='utf-8')
 path=R/'creative/ANIMATION_KNOWLEDGE_BANK.md';text=path.read_text(encoding='utf-8');start=text.index('**Current state:**',text.index('### 10 Farpoint Station'));end=text.index('\n\n',start)
 current="**Current state:** v1 motion was rejected as invisible; the user confirmed v2 cloud visibility. V3 lower clouds/shadows still did not read as another planetary phenomenon. The user invoked the completion prompt; [v4](../music/farpoint-animation-v4/README.md) now delivers a genuine sixty-second 720p candidate and exact 180-second review with aurora, sparse storms, fixed-star variation, linked reflections and minute-wide station activity. Technical gates passed; assistant inspected stills, not continuous playback. User artistic review and subsequent 4K remain pending."
 text=text[:start]+current+text[end:]
 text=text.replace('these remain unrendered proposals.','v4 now implements them as candidates awaiting user playback review.')
 text=text.replace('and any future lamp animation should make their behaviour coherent.','v4 now links their complete bright cores and local haze to the desk lamp. Brightness-aware core masking excludes surrounding dark glass, avoiding rectangular dim patches.')
 new="""
- Extending the direct cloud excerpt required a new coverage/renewal design. V4 partitions extracted optical clouds into separate feathered formations, preserves v2 velocities, and staggers sixty-second lifetimes with zero-opacity resets. This avoids blending nearby copies of the entire weather field. The composite arrangement changes: exact source-array retention is not identical frames or artistic acceptance. Inspect local fading/overlap and reconstructed terrain in playback.
- The first aurora draft read as a comb in full-frame stills. Seeded irregular spacing, widths/heights, gentle curvature, gaps and softened detail corrected it before delivery. Minute-periodic transport and masking protect the original limb; fictional plausibility is separate from physical simulation.
- Storms must be placed in the cloud present at their event time. The middle event initially hit thin cloud and was moved within the extant optical formation. Pixel changes support but do not establish visibility. See [v4 review](../music/farpoint-animation-v4/visual-review.json) and delivery evidence.

"""
 at=text.index('## Render and delivery improvements to retain');text=text[:at]+new+text[at:]
 text=text.replace("Farpoint 10's v2 cloud visibility is user-confirmed; v3 additional detail awaits review and no revised seamless loop has been delivered.","Farpoint 10's v2 cloud visibility is user-confirmed; v4's complete minute and new effects await playback review, with technical delivery recorded.")
 path.write_text(text,encoding='utf-8')
 path=R/'music/farpoint-animation-v3/README.md';text=path.read_text(encoding='utf-8');text=text.replace('This follow-up requested a prompt only; none of those new proposals has been rendered.','That follow-up requested a prompt only. The user subsequently invoked it; the new effects and complete minute are delivered as the [v4 candidate](../farpoint-animation-v4/README.md), awaiting playback review.');path.write_text(text,encoding='utf-8')
 print('Delivery manifest and current scene, pipeline, knowledge bank and AGENTS status updated')

if __name__=='__main__':main()
